oro_entity_config:
    activity:
        entity:
            items:
                activities:
                    options:
                        priority:           250
                        auditable:          false
                    form:
                        type:               oro_entity_extend_multiple_association_choice
                        options:
                            block:          associations
                            required:       true
                            label:          oro.activity.activities
                            association_class: activity
