parameters:
    oro_activity.entity_extend.dumper_extension.class: Oro\Bundle\ActivityBundle\Tools\ActivityExtendConfigDumperExtension

services:
    oro_activity.entity_extend.dumper_extension:
        class: %oro_activity.entity_extend.dumper_extension.class%
        parent: oro_entity_extend.config_dumper_extension
        tags:
            - { name: oro_entity_extend.dumper_extension }
