parameters:
    oro_activity.entity_extend.dumper_extension.class: Oro\Bundle\ActivityBundle\Tools\ActivityExtendConfigDumperExtension

services:
    oro_activity.entity_extend.dumper_extension:
        class: %oro_activity.entity_extend.dumper_extension.class%
        arguments:
            - @oro_entity_config.config_manager
        tags:
            - { name: oro_entity_extend.dumper_extension }
